disabled = false
languageCode = "zh-tw"
languageName = "Traditional Chinese (Taiwan)"
weight = 4
title = "詩夢凜的小旮旯"

[params]
displayName = "繁體中文"
isoCode = "zh-tw"
rtl = false
dateFormat = "2 January 2006"
