disabled = false
languageCode = "zh-cn"
languageName = "Traditional Chinese (Taiwan)"
weight = 1
title = "诗梦凛的小旮旯"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2 January 2006"
